Added docs for /cosmetics endpoint
SevenTV/ServerGo pull request #172
Opened 2022-01-03 06:37 UTC by MrAuro

All information I found about it was by looking at this repo or by looking at how it is used at https://github.com/SevenTV/SevenTV 

![Okayeg](https://cdn.7tv.app/emote/603caa69faf3a00014dff0b1/1x)

2022-01-03 11:00 UTC, Excellify commented
I believe the paints are going to have some changes. Drop_shadow will become drop_shadows and be able to include multiple. Some of the properties are optional, while some are not. 
[Here](https://github.com/SevenTV/SevenTV/blob/ca0a165b5b990932311e30011497a377bc5752ee/src/Sites/app/SiteApp.tsx#L170) is how the extension builds the style from the json. 
Also believe pr's should be to dev, not master.

![image](https://user-images.githubusercontent.com/49245223/147923270-db298dfc-5a2c-480d-b2e5-cc2f2e422cf3.png)

2022-01-03 11:05 UTC, TroyDota commented
@AnatoleAM will have to see if this is the correct design for the API documents.
This repo is planed to be deprecated within the next few months but adding the docs now sounds like a good idea.

2022-01-03 18:28 UTC, AnatoleAM requested changes
This is fine to document, however it's worth noting these two things are changing:

- The `animation` field will be dropped
- The `drop_shadow` field will be deprecated, in favor of `drop_shadows` (same structure, but as an array)

It may also be worth noting that
- The `color` field may be null
- Colors are all RGBA stored in a 32-bit integer and provide an example on how to decode them (i.e a javascript code sample)

2022-01-03 22:06 UTC, Excellify commented on docs/rest-api.md
> +			"function": "linear-gradient",
Might also be an idea to note the 3 accepted function: 

1. linear-gradient
2. radial-gradient
3. url

2022-01-04 00:29 UTC, Excellify approved these changes
Looks good to me

2022-01-10 20:19 UTC, AnatoleAM approved these changes

2022-01-10 20:20 UTC, merged