Notification System
SevenTV/ServerGo pull request #42
Opened 2021-06-29 21:32 UTC by AnatoleAM

Implementing a complete notification system, creating a direct line of communication to end-users for alerts such as moderation actions or other messages relevant to a user or group of users.

2021-07-02 07:02 UTC, TroyDota requested changes

2021-07-02 07:02 UTC, TroyDota commented on src/utils/utils.go
You can just compare 2 objectids via equal.

2021-07-02 07:02 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/query/user.go
> +func (r *UserResolver) Notifications() ([]*notificationResolver, error) {
Can this not be done with an aggregated mongo function?

2021-07-02 07:05 UTC, AnatoleAM commented on src/mongo/datastructure/datastructure.go
> +	ReadBy  []primitive.ObjectID `json:"read_by" bson:"read_by"` // The users who have read this notification
ReadBy could be ignored if the notification is set as an announcement

2021-07-02 07:07 UTC, TroyDota commented on src/mongo/datastructure/datastructure.go
> +	ReadBy  []primitive.ObjectID `json:"read_by" bson:"read_by"` // The users who have read this notification
Its far easier to have 2 collections and query via aggregated function.

2021-07-02 07:11 UTC, TroyDota commented on src/mongo/datastructure/datastructure.go
> +	ReadBy  []primitive.ObjectID `json:"read_by" bson:"read_by"` // The users who have read this notification
Also a new user will by default receive all notifications. And if let's say they acquire a role that will get notified of events that were specific to that role in the past.

Best approach I think it's too have a notification. And then to have a table of notification recipients and make one for each user who will get the notification. And once they read it you update the state of that object making it so they don't get pinged again.

2021-07-02 07:12 UTC, TroyDota commented on src/mongo/datastructure/datastructure.go
> +	ReadBy  []primitive.ObjectID `json:"read_by" bson:"read_by"` // The users who have read this notification
And then also don't create notifications for all users at the same time. Do a Cron job.

2021-07-02 21:11 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/query/user.go
> +func (r *UserResolver) Notifications() ([]*notificationResolver, error) {
An aggregation pipeline could be explored, although those can be time consuming to get right. Something to consider for later?

2021-07-02 21:21 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/query/user.go
> +func (r *UserResolver) Notifications() ([]*notificationResolver, error) {
Is there a reason we need to push this out immediately and not get it right the first time?

2021-07-02 21:23 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/query/user.go
> +func (r *UserResolver) Notifications() ([]*notificationResolver, error) {
What's wrong with this approach exactly? It's still a single query to the DB, just that the program does the work instead of Mongo.

2021-07-02 21:25 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/query/user.go
> +func (r *UserResolver) Notifications() ([]*notificationResolver, error) {
Yes, mongo doing the work is better here i think.

2021-07-02 21:28 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/query/user.go
> +func (r *UserResolver) Notifications() ([]*notificationResolver, error) {
I'm not sure, mongo pipelines are nice for a bunch of things but cross-collection aggregations are really difficult to get right. I have doubts it's worth spending 4-6 hours on it at this time

2021-07-03 19:28 UTC, TroyDota requested changes

2021-07-03 19:28 UTC, TroyDota commented on src/mongo/mongo.go
> +	_, err = Database.Collection("notifications").Indexes().CreateMany(ctx, []mongo.IndexModel{})
No indexes?

2021-07-03 19:28 UTC, TroyDota commented on src/mongo/datastructure/datastructure.go
> +var EmoteVisibilitySimpleMap = map[int32]string{
why is this here?

2021-07-03 19:28 UTC, TroyDota commented on src/server/api/actions/emotes.go
> +var Emotes emotes = emotes{}
what does this do?

2021-07-03 19:28 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/query/user.go
> +	outerLock.Lock()
locking?

2021-07-03 19:50 UTC, AnatoleAM commented on src/server/api/actions/emotes.go
> +var Emotes emotes = emotes{}
I plan to standardize actions on objects to avoid duplicating code (since everything happens in the context of GQL at the moment), that wasn't meant to be pushed now tho FeelsDankMan

2021-07-03 19:51 UTC, AnatoleAM commented on src/mongo/datastructure/datastructure.go
> +var EmoteVisibilitySimpleMap = map[int32]string{
It was moved from restutil.go so that it can be utilized in other places if needed, ie to format messages containing human readable visibility instead of bitmask

2021-07-03 20:01 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/query/user.go
> +	outerLock.Lock()
It's for the goroutine inside the for loop, it waits for the iterator to complete then queries every emote/user, so this lock is here to make sure the data has all been received before moving onto the resolution

2021-07-03 20:03 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/query/user.go
> +	outerLock.Lock()
No, you lock twice, once at the top and again this is supposed to be an unlock?

2021-07-03 20:06 UTC, AnatoleAM commented on src/mongo/mongo.go
> +	_, err = Database.Collection("notifications").Indexes().CreateMany(ctx, []mongo.IndexModel{})
I've added indexes for `target` and `notification` under the "notifications_read" collection, but I believe no index is needed for the notification object, as this collection is only ever read by ObjectID

2021-07-03 20:07 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/query/user.go
> +	outerLock.Lock()
The upper Lock() call triggers the lock, while the second is there to await the completion of all goroutines inside the loop

2021-07-03 20:09 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/query/user.go
> +	outerLock.Lock()
FeelsDankMan, no. YOU LOCK THE OUTER LOCK TWICE THIS WILL CAUSE A DEADLOCK
https://github.com/SevenTV/ServerGo/blob/b4b7a15dc572fc3f45098e715c2d587da6ef6091/src/server/api/v2/gql/resolvers/query/user.go#L620
https://github.com/SevenTV/ServerGo/blob/b4b7a15dc572fc3f45098e715c2d587da6ef6091/src/server/api/v2/gql/resolvers/query/user.go#L704

2021-07-03 20:11 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/query/user.go
> +	outerLock.Lock()
But it doesn't work if you don't lock twice? Because the initial lock call doesn't stop code execution. If i do this the resolvers return null

2021-07-03 20:11 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/query/user.go
> +	outerLock.Lock()
the locking thing needs to change. All of it.

2021-07-04 00:08 UTC, merged