Entitlements
SevenTV/ServerGo pull request #69
Opened 2021-07-21 23:35 UTC by AnatoleAM

Implementing Entitlements into the API, a system which defines access to an item/resource, such as an Emote Set, Badge, Role, etc.

2021-07-23 05:34 UTC, TroyDota reviewed
GIGACHAD

2021-07-23 05:34 UTC, TroyDota commented on src/mongo/datastructure/entitlement.go
> +	Data interface{} `json:"data" bson:"data"`
Make this a bson.Raw which allows us to unmarshal later.

2021-07-23 05:34 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +		Upsert: &upsert,
We have a util which makes bool pointers for this reason.

2021-07-25 04:07 UTC, AnatoleAM commented
Not ready for merge but at this point is virtually complete; Role entitlement is done, just needs entitlement implementation of badges

2021-07-25 08:03 UTC, TroyDota requested changes
? 600 lines is easy

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +	log.Infof("<EntitlementBuilder:%v> [Kind: %v] [User: %v] %v", b.Entitlement.ID, b.Entitlement.Kind, b.Entitlement.UserID, str)
Use log fields

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +	log.Errorf("<EntitlementBuilder:%v> [Kind: %v] [User: %v] %v", b.Entitlement.ID, b.Entitlement.Kind, b.Entitlement.UserID, str)
Same with this.

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/actions/users.go
> +func (b UserBuilder) FetchEntitlements(kind *datastructure.EntitlementKind) ([]EntitlementBuilder, error) {
Allow context to be passed at this point?

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/ban.go
>  	return &response{
Ok? Status?

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/ban.go
>  	return &response{
Ok? Status?

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/emote-restore.go
>  	return &response{
Ok? Status?

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/v2/gql/scheme/scheme.gql
> +  # Whether or not the request succeeded
We must be careful changing GQL structure here since this will break any 3rd party apps that depend on it.

2021-07-25 08:03 UTC, TroyDota commented on src/server/api/v2/gql/scheme/scheme.gql
> +  # Whether or not the request succeeded
Perhaps we dont?

2021-07-25 08:06 UTC, AnatoleAM commented on src/server/api/v2/gql/scheme/scheme.gql
> +  # Whether or not the request succeeded
Forgot to push actually, meant to deprecate this not remove it

2021-07-25 08:08 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/mutation/ban.go
>  	return &response{
"Status" doesn't make sense in the context of GQL, as it's either 200 OK or some error, hence the change to "OK" to signify success

2021-07-25 20:27 UTC, AnatoleAM commented on src/server/api/actions/users.go
> +func (b UserBuilder) FetchEntitlements(kind *datastructure.EntitlementKind) ([]EntitlementBuilder, error) {
The context is passed during the initial creation of the entitlement builder, is there a benefit to passing it again?

2021-07-26 06:31 UTC, TroyDota requested changes
Xd

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +	role := datastructure.GetRole(ub.User.RoleID)
GetRole?

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +		log.WithError(err).Error("bson")
No, return an error?

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +		log.WithError(err).Error("bson")
Return an error

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +		log.WithError(err).Error("bson")
Return an error

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +		log.WithError(err).Error("bson")
Return an error

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +	x := map[datastructure.EntitlementKind]func() error{
Use a switch statement

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +func (b EntitlementBuilder) syncSubscription() error {
Is this uncompleted?

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +	}).Infof(str)
Info f should be just info since no format strings

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/actions/entitlements.go
> +	}).Errorf(str)
Same as above

2021-07-26 06:31 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/report.go
> -		Status:  200,
Do not remove this. We must support this status field

2021-07-26 21:35 UTC, AnatoleAM commented on src/server/api/v2/gql/resolvers/mutation/report.go
> -		Status:  200,
No service other than the web app implements it and it doesn't check for its value. This change would merely make it return zero, which is only to avoid errors for clients with an older version of the app cached.

2021-07-26 23:16 UTC, AnatoleAM commented on src/server/api/actions/entitlements.go
> +func (b EntitlementBuilder) syncSubscription() error {
It slipped out as a design choice, opted to query entitlements directly when considering things (i.e user roles are now determined by entitlement, sorted by the entitlement that contains the role with the highest position)

2021-07-27 01:01 UTC, AnatoleAM commented on src/server/api/actions/entitlements.go
> +		log.WithError(err).Error("bson")
Not possible due to the nature of the Builder-type structs, they're meant to be chainable. In this case the error is irrelevant anyway, it will just be logged and the data will just be an empty byte slice

2021-07-27 11:29 UTC, TroyDota requested changes

2021-07-27 11:29 UTC, TroyDota commented on k8s/ingress/7tv-ingress.yaml
> +    - host: egvault-stage.7tv.app
Not part of this PR.

2021-07-27 11:29 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/entitlement.go
> +	return &response{
Add status 200 to this so that older versions still are accepting.

2021-07-27 11:29 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/entitlement.go
> +	return &response{
Add status 200 to this so that older versions still are accepting.

2021-07-27 11:29 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/meta.go
> +		OK:      true,
Add status 200 to this so that older versions still are accepting.

2021-07-27 11:29 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/emote-restore.go
> +		OK:      true,
Add status 200 to this so that older versions still are accepting.

2021-07-27 11:29 UTC, TroyDota commented on src/server/api/v2/gql/resolvers/mutation/report.go
> +		OK:      true,
Add status 200 to this so that older versions still are accepting.

2021-07-27 16:21 UTC, AnatoleAM commented on k8s/ingress/7tv-ingress.yaml
> +    - host: egvault-stage.7tv.app
eShrug doesn't matter i guess

2021-07-27 17:43 UTC, TroyDota commented on k8s/ingress/7tv-ingress.yaml
> +    - host: egvault-stage.7tv.app
does should be a separate commit so we can revert if it breaks.

2021-07-27 17:52 UTC, TroyDota approved these changes

2021-07-27 17:52 UTC, TroyDota commented
Ill test on stage.

2021-07-27 18:01 UTC, merged